### PR TITLE
Fix doctest

### PR DESCRIPTION
**Pull request by abadger**
Configure travis to run some tests on the documentation and fixed a few doctests and broken links.

### CODE REVIEW

**Comment by wearpants** [comment]
squashing ;-)

**Comment by wearpants** [comment]
ugh weird: build passes -> squash & merge -> build fails. will poke around later today or tomorrow, and avoid doing this on mobile. :-(

**Comment by abadger** [comment]
Looks like flake8 and pyflakes updated.  So must be new tests in pyflakes
that are breaking the build.

**Comment by abadger** [comment]
Waiting to make sure that this passes travis and then I'll merge:
https://github.com/wearpants/twiggy/pull/76

**Pull request merged**
